Syntax highlighting
jjaniec/21sh pull request #19
Opened 2018-08-29 18:17 UTC by jjaniec

Syntax highlighting

On mettras ca avec le boulot de gamouche quand on mergera sa branche

2018-08-30 13:22 UTC, SebastienBruckert commented on srcs/exec/manage_path.c
> -	ft_putstr_fd("21sh: ", 2);
WHERE ARE THEY NOW ???

2018-08-30 13:23 UTC, SebastienBruckert requested changes
21sh: review not found.

2018-08-30 16:48 UTC, jjaniec commented
C'est fix lol

2018-08-30 18:56 UTC, Gamouche approved these changes
Travail incroyable
1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

2018-08-31 10:29 UTC, SebastienBruckert approved these changes

2018-08-31 11:05 UTC, cgaspart approved these changes

2018-08-31 12:59 UTC, merged

2018-09-02 11:44 UTC, Gamouche reviewed
verifie t malloc