Expansions
jjaniec/21sh pull request #27
Opened 2018-09-25 16:51 UTC by jjaniec

- ```$HOME``` and ```~``` type expansions
- Tests for both
- Fix newline after empty element (like ```""\n```) being skipped

2018-09-25 18:03 UTC, Gamouche approved these changes

2018-09-25 18:03 UTC, Gamouche commented
slt

2018-09-26 10:24 UTC, SebastienBruckert requested changes
All good, juste le makefile !

2018-09-26 10:24 UTC, SebastienBruckert commented on Makefile
> +CFLAGS = -Wall -Wextra -g -D_GNU_SOURCE -std=c11 #-Werror
Wow what's that boy, on et en C11 maintenant, en virant les warnings ? x)
On a pas besoin du -std=c11, et on peut laisser le -Werror, ca compile parfaitement quand meme

2018-09-26 11:27 UTC, jjaniec commented on Makefile
> +CFLAGS = -Wall -Wextra -g -D_GNU_SOURCE -std=c11 #-Werror
C'est quoi le probleme ? Si ca peut nous faire gagner du temps en evitant de devoir faire (void)machin a chaque fois qu'on test des trucs pour la suite et si on le remet a la fin quand on rends, ou est le probleme ? Je comprends pas

2018-09-26 12:00 UTC, SebastienBruckert commented
Arf ouais bon bah why not, faudra pas oublier de le virer a la fin :)

Le mer. 26 sept. 2018 à 13:27, Joffrey Janiec <notifications@github.com> a
écrit :

> *@jjaniec* commented on this pull request.
> ------------------------------
>
> In Makefile
> <https://github.com/jjaniec/21sh/pull/27#discussion_r220523724>:
>
> > @@ -168,7 +169,7 @@ TESTS_SRCS_OBJS_NAME = $(subst ./objs/main.o,,$(OBJ)) $(TESTS_OBJ) $(addprefix $
>
>  ###### COMPILATION ######
>  CC = gcc
> -CFLAGS = -Wall -Wextra -Werror -g -D_GNU_SOURCE -std=c11
> +CFLAGS = -Wall -Wextra -g -D_GNU_SOURCE -std=c11 #-Werror
>
> C'est quoi le probleme ? Si ca peut nous faire gagner du temps en evitant
> de devoir faire (void)machin a chaque fois qu'on test des trucs pour la
> suite et si on le remet a la fin quand on rends, ou est le probleme ? Je
> comprends pas
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/jjaniec/21sh/pull/27#discussion_r220523724>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AYnwtnq9W4rbbApMq6TSAdfxyA3AKDybks5ue2SRgaJpZM4W5DpZ>
> .
>

2018-09-26 13:33 UTC, Gamouche commented on Makefile
> +CFLAGS = -Wall -Wextra -g -D_GNU_SOURCE -std=c11 #-Werror
je n'aime PAS le flag -Werror lol
j'aime BIEN le flag c11  :)

2018-09-27 13:21 UTC, cgaspart approved these changes
Good

2018-09-27 14:52 UTC, merged