Shell script
jjaniec/21sh pull request #28
Opened 2018-09-26 13:33 UTC by SebastienBruckert

Add integration of shell script, with this : 
 `IF` `THEN` ` ELIF` `ELSE` `WHILE` `DO` `DONE`
Builtin `test` and its alias `[` (On WIP)
Remake of the AST constructor and script / command error handler.
Management of sub_ast.

2018-09-26 13:44 UTC, Gamouche approved these changes

2018-09-27 14:29 UTC, jjaniec requested changes
```
16:07:12 ERROR srcs/script/is_script_complete.c:28: There is an error here: if
There is an error in your script.
$ if ls; then ls; fi;
```
la syntaxe me parait pourtant bonne par rapport a ce que tu m'as mis sur slack

par contre le ```[``` si c'est wip mets le dans une branche a part sinon on va le merge avec celle ci 
(parce que pour l'instant ```if [ 1 ]; then ls; fi;``` n'execute pas ```ls```)

deso

2018-09-27 14:29 UTC, jjaniec commented on srcs/ast/ast_constructor.c
> +	t_ast		*save_root;
Je pense que tu as du oublier d'enlever cette variable

2018-09-27 14:47 UTC, SebastienBruckert commented on srcs/ast/ast_constructor.c
> +	t_ast		*save_root;
En ce qui concerne `if [ 1 ]; then ls; fi`, c'est normal. `[ 1 ]` renvoie de fait 1, qui est une valeur d'erreur en shell. `[ 0 ]` est du valeur de reussite ;) 
Le builtin test est en WIP ( et j'ai fait une branche a partir de ce dernier commit) uniquement pour les comparaisons entre int. Sinon il fonctionne normalement, mais je ferai plus de tests a son sujet.
 
Par contre en effet, le `if ls; then ls; fi;` me parait tres etrange, je vais aller voir ca !

2018-09-27 15:02 UTC, jjaniec commented on srcs/ast/ast_constructor.c
> +	t_ast		*save_root;
oui je sais pour le ```[ 1 ]``` mais sh l'execute alors j'ai pensé que ca n'etait pas normal ....

2018-09-27 15:15 UTC, SebastienBruckert commented on srcs/ast/ast_constructor.c
> +	t_ast		*save_root;
sh exectue n'importe quel builtin test qui comporte au moins un argument. Dans un soucis de simplicite, de compatabilite avec des vieux tests et de logique, j'ai decide de changer ce point en disant que lorsqu'il y a `test N` ou `[ N ]`, la valeur de retour est `N`. Mais je peux changer ca pour revenir a quelque chose de plus posix

2018-09-27 15:49 UTC, SebastienBruckert commented on srcs/ast/ast_constructor.c
> +	t_ast		*save_root;
Fix !

2018-09-27 16:24 UTC, jjaniec commented on srcs/ast/ast_constructor.c
> +	t_ast		*save_root;
Je suis pas sur que ce soit ca et je verra mieux de faire ca comme sh et zsh perso

2018-09-27 16:28 UTC, jjaniec commented
```
18:16:55 ERROR srcs/script/is_script_complete.c:28: There is an error here: if
There is an error in your script.
$ if if non; then echo lol; fi; then ls; fi;
```
```
sh-3.2$ if if non; then echo lol; fi; then ls; fi
sh: non: command not found
21sh ...
```
Regarde le log de travis sur linux

2018-09-30 15:03 UTC, jjaniec approved these changes

2018-10-01 07:41 UTC, merged