Autocomplete
jjaniec/21sh pull request #29
Opened 2018-09-26 20:45 UTC by cgaspart

Autocomplete path in command line integration

2018-09-27 13:14 UTC, SebastienBruckert requested changes
Tout bon, juste un mini truc inutile ;)

EDIT j'ai rien dit !

2018-09-27 13:14 UTC, SebastienBruckert commented on srcs/autocomplete/autoc_dir.c
> +	j = 0;
Codacy a raison sur ce point !
`int j` ne sert a rien ;)

2018-09-27 13:16 UTC, SebastienBruckert approved these changes
All good

2018-09-27 19:34 UTC, Gamouche requested changes
regarde slack jvais pas tout repeter (jtm tqt)

2018-09-28 16:27 UTC, jjaniec reviewed
slack lol (jtm tqt)

2018-10-01 15:06 UTC, closed without merging