Builtin history
jjaniec/21sh pull request #30
Opened 2018-09-27 16:21 UTC by Gamouche

builtin history 
/*
**	Without option : print the history list with an index.
**	--clear : empty the history.
**	--save : save the history into a file.
**	history n : print the last 'n' elements.
**	-d n : deletes the element with the index 'n'.
*/

testez et approuvez si ca vous va :)

2018-09-28 15:50 UTC, jjaniec approved these changes
testé et approuvé

2018-09-29 11:52 UTC, SebastienBruckert requested changes
`history -d 0`
-> Ca segfault
Sinon tout a l'air cool hormis le `his->prev = NULL` dans un fichier (voir codacy + mon commentaire) ;)

2018-09-29 11:52 UTC, SebastienBruckert commented on srcs/builtin/builtin_history.c
> +	his->prev = NULL;
Codacy a raison, si ta boucle fini et que la condition `his != NULL` devient fausse ( et donc que `his == NULL`), en faisant `his->prev = NULL`, ca va segfault

2018-09-29 14:13 UTC, SebastienBruckert approved these changes

2018-09-30 15:01 UTC, merged