Env handling & local/internal variables
jjaniec/21sh pull request #36
Opened 2018-10-03 15:55 UTC by jjaniec

- Remake environnement handling w/ a linked list
- Add support for local & internal variables
- Remake cd, env (w/o command execution yet), (un)setenv (not posix yet)

2018-10-04 08:23 UTC, cgaspart reviewed
- setenv: Pas d'usage quand setenv est appelé sans argument.

- '"$ setenv LOX=GOD" : Cela créé bien la variable mais en laissant 2 case vides:
"LC_CTYPE=en_US.UTF-8
LSCOLORS=Gxfxcxdxbxegedabagacad
_=/tmp/21sh/./42sh


LOX=GOD"

- "$ echo $LOX" : Affiche une ligne vide.

- "$ unsetenv LOX" unset bien la variable mais il y a toujours deux cases vides.

Sorry :(

2018-10-04 10:24 UTC, Gamouche commented
plusieurs bugs dans env setenv unsetenv et cd. On en parle a l'ecole GROUILLE TOI squalala nous sommes partiiiis

2018-10-07 18:12 UTC, SebastienBruckert requested changes
SHLVL ne se met pas a jour
Lorsque OLDPWD est mauvais (`OLDPWD=lol`), cd ne doit pas afficher le path vers lequel il va:
```
sh-3.2$ cd -
sh: cd: lol: No such file or directory
-----------
$ cd -
lol
42sh: lol: does not exists
```
exit fait un abort error free malloc tout ca tout ca quand il n'y a aucune variable d'environnement
Les variables locales ne s'affichent pas.
Lorsque l'on supprime toutes les variables d'environnement, que l'on en recree une, et qu'on la supprime, elle ne s'affiche pas + abort error a l'exit

2018-10-08 13:24 UTC, Gamouche requested changes
$ setenv =      => ligne vide dans env

$ setenv ==    => ligne vide dans env

$ setenv ===   => ligne vide dans env

$ setenv ==a   => ligne vide dans env

(pas teste plus loin lol)

SHLVL ne se met pas a jour

Si on donne des arguments a env, il dit rien

$ setenv 'A$BC=value'  (entre simples quotes)  => pour le echo c'est pas possible

les pipes marchent pas

2018-10-09 11:08 UTC, closed without merging