Leaks, fix, break, continue, command not found
jjaniec/21sh pull request #43
Opened 2018-10-12 13:48 UTC by SebastienBruckert

Remove a lot of leaks.
Change leaking get_next_line from cyfermie by sbrucker's one, which doesn't leak 8).
Add comments with the `#`.
Add the possibility to load and execute a file, if it is as an argument and if the flac `-c` is not activated. No interactive mode when executing from a file. Only works with one file.
Add shebang support.
Add `break` and `continue` statement. If not in a loop, they do nothing.
When a command is not found, set the return value on `-1`.

2018-10-13 10:08 UTC, jjaniec commented
Tu farm les commits ? lol je test ca lundi apres le rush de js

2018-10-16 11:23 UTC, jjaniec requested changes
Avec ca:
```while [ 1 ]; do echo lol; ls /tmp/doesnotexist && ls ;  done;```
le 2eme ls n'est pas exectué,
mais avec ca:
```while [ 1 ]; do echo lol; ls /tmp/doesnotexist && break ;  done;```
le break casse quand meme le while,

Aussi je trouverais ca dommage de pas pouvoir break ou continue dans un if parceque ca peut etre bien pratique

2018-10-16 11:34 UTC, SebastienBruckert commented
Exact pour le break qui casse le while, je note !
En ce qui concerne les IF, ce n'est pas du tout intégrer de base, le IF
n'étant pas une boucle cela n'a pas de sens de break ou de continue. En
revanche, je peux intégrer le builtin `:` qui ne fait tout simplement rien

On Tue, Oct 16, 2018, 1:23 PM Joffrey Janiec <notifications@github.com>
wrote:

> *@jjaniec* requested changes on this pull request.
>
> Avec ca:
> while [ 1 ]; do echo lol; ls /tmp/doesnotexist && ls ; done;
> le 2eme ls n'est pas exectué,
> mais avec ca:
> while [ 1 ]; do echo lol; ls /tmp/doesnotexist && break ; done;
> le break casse quand meme le while,
>
> Aussi je trouverais ca dommage de pas pouvoir break ou continue dans un if
> parceque ca peut etre bien pratique
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jjaniec/21sh/pull/43#pullrequestreview-165108160>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AYnwtmpDxGLiEsFQiPeiK9BanA8THh-Kks5ulcGtgaJpZM4XZgrZ>
> .
>

2018-10-16 11:44 UTC, jjaniec commented
Tu pense que ca te prendrais beaucoup de temps de le gérer ?
Parce que c'est plutot utile dans les cas ou on utilise des boucles infinies du style quand on veut casser un while dès qu'un fichier existe avec une commande du style
```while [ 1 ]; do echo something; if ls /tmp/lock; then break; fi; done;```

Aussi je viens de voir qu'il y a un petit souci avec les subprompts et les tokens de scripts
genre quand on fait
```
while [ 1 ]; do ls; don\
... $ e;
There is an error in your script.
```
alors qu'avec une commande ca marche bien
```
$ l\
... $ s
le ls
```
:(

2018-10-16 11:47 UTC, SebastienBruckert commented
Normalement quand on met un if dans un while, avec un break dans le if, le
break fonctionne et quitte le while.
Et si tu essaies le subprompt avec un `&&` par exemple, même merde ?

On Tue, Oct 16, 2018, 1:44 PM Joffrey Janiec <notifications@github.com>
wrote:

> Tu pense que ca te prendrais beaucoup de temps de le gérer ?
> Parce que c'est plutot utile dans les cas ou on utilise des boucles
> infinies du style quand on veut casser un while dès qu'un fichier existe
> avec une commande du style
> while [ 1 ]; do echo something; if ls /tmp/lock; then break; fi; done;
>
> Aussi je viens de voir qu'il y a un petit souci avec les subprompts et les
> tokens de scripts
> genre quand on fait
>
> while [ 1 ]; do ls; don\
> ... $ e;
> There is an error in your script.
>
> alors qu'avec une commande ca marche bien
>
> $ l\
> ... $ s
> le ls
>
> :(
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jjaniec/21sh/pull/43#issuecomment-430205939>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AYnwtmPsQxfjUmDOyXv0bHXgMM_Ke-oxks5ulcaegaJpZM4XZgrZ>
> .
>

2018-10-16 11:54 UTC, jjaniec commented
Ah d'accord parceque je me suis dis que ce n'etait pas prevu quand j'ai vu ``` If not in a loop, they do nothing.```

Bah du coup ```while [ 1 ]; do if [ 1 ]; then break; fi; done;``` boucle a l'infini

Par contre
```
$ while [ 1 ]; do ls &&
AND $ ls; done
```

marche

2018-10-16 12:02 UTC, jjaniec commented
Aussi un autre petit truc moins grave on dirait que l'option -d du builtin alias renvoie 0 si le parametre est un symlink vers directory

sur sh:
```
[ -d /tmp ] && ls
42sh                            codecov.yml                     ft_printf                       sonar-project.properties        tests
```
et sur notre shell le ls ne s'execute pas

2018-10-16 12:13 UTC, SebastienBruckert commented
Okay merci des infos je fix tout a mon retour !

On Tue, Oct 16, 2018, 2:02 PM Joffrey Janiec <notifications@github.com>
wrote:

> Aussi un autre petit truc moins grave on dirait que l'option -d du builtin
> alias renvoie 0 si le parametre est un symlink vers directory
>
> sur sh:
>
> [ -d /tmp ] && ls
> 42sh                            codecov.yml                     ft_printf                       sonar-project.properties        tests
>
> et sur notre shell le ls ne s'execute pas
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jjaniec/21sh/pull/43#issuecomment-430210783>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AYnwtgbI5Y284Kz4nRX81hG4GZZRmongks5ulcrkgaJpZM4XZgrZ>
> .
>

2018-10-24 15:55 UTC, Gamouche requested changes
while [ 1 ] ; do ; pwd ; break ; done

CA MARCHE PAS BIEN

`if [ -42 ] ; then pwd ; fi`   `sh` accepte `-42` mais pas toi, perso ca me va mais toi qui voit

$ while [ 1 ] ; do  pwd ; ls || break ; done
Le break ne devrait pas se lancer !!!!!!!!!!!!!!!!!!!!!!!

pour un fichier qui contient `ls\n` ou `ls` on peut faire `./42sh file` . mais si le fichier contient `ls\n\n` alors ca compte comme une erreur. Normal ?

Le mec chiant qui lit le code : (enfin survole plutot)
builtin_test_pare.c - lignes 38 et 73 - utilises SH_NAME au lieu de 21sh (pareil main.c ligne 112)
dans read_file() (main.c) tu ne verifies pas le retour de gnl (si -1 alors go exit)

si tu veux faire les changements des allocs, voila les nouvelles :
ft_xmalloc.c
ft_xmemalloc.c
ft_xrealloc.c
ft_xstrdup.c
ft_xstrjoin.c
ft_xstrnew.c

2018-10-28 14:48 UTC, Gamouche approved these changes

2018-10-28 16:51 UTC, cgaspart approved these changes
Good

2018-10-28 17:15 UTC, jjaniec approved these changes

2018-10-28 17:20 UTC, merged