Fixeuuuuh
jjaniec/21sh pull request #44
Opened 2018-10-21 15:33 UTC by Gamouche

Multiple fixes :
- fix a leak when modifying the value of an alias that already exist
- fix a bug when resizing the window with a command on multiples lines
- fix ctrl+L
- fix ctrl+U
- Now the shell cannot have a command larger than the window's size
- fix a bug when the length of the clipboard was not always updated
- add builtin unalias doing alias -d
- changing allocation functions by ft_xmalloc, ft_xrealloc, ft_xmemalloc, ft_xstrdup, ft_xstrjoin, ft_xstrnew
- builtin exit and ctrl+D now write "exit"
- rework of the function init_termcaps_strings()
- fix a bug when running through the history with arrows up/down, when an history command was built with the quotes subprompt
- fix the bug when a directory is used as a binary file ("srcs" was/is command not found, but "srcs/" was used as a binary file)

N'hesitez pas a tester cette liste, et bien entendu verifier que ca n'entre pas en conflit avec les autres features normalement intouchees.

2018-10-23 19:43 UTC, jjaniec reviewed
je test ca demain mais apparement y'a un truc qui va pas dans le exit d'apres travis sur loonix, tu checkeras ```./42sh -c exit```

2018-10-24 11:14 UTC, SebastienBruckert requested changes
Quand on fait `./42sh -c exit`, tu ecris quand meme exit. Ca pourrait etre cool de ne pas l'ecrire quand l'option `-c` est validée. C'est un tout pitit detail ^^

Sinon c'est tout bon pour moi niveau fonctionnalités, bien joué !

2018-10-24 14:30 UTC, SebastienBruckert approved these changes

2018-10-24 15:11 UTC, cgaspart commented
Gj, j'attend la que ça soit merge pour ajouter tes fonctions à la hash_table

2018-10-24 15:11 UTC, cgaspart approved these changes

2018-10-24 18:14 UTC, merged