Hash table
jjaniec/21sh pull request #45
Opened 2018-10-22 16:06 UTC by cgaspart

Implementation de la table de hash.

- syntax_highlighting with hash_table: OK
- exec with hash_table: OK

Cas d'update:
- La variable PATH à été modifié dans l'env
- Un des PATH à été modifié

Norme and leaks should be ok :)
Merci de tester si tout est ok pour vous 👍 

Peace ☮️

2018-10-23 19:28 UTC, jjaniec approved these changes
Nickel on sent la diff dans la colo syntaxique

2018-10-24 11:06 UTC, SebastienBruckert requested changes
J'ai trouve un bug qui provient plus des expansions que de ton code, mais je le note ici quand meme:
`setenv PATH=$PATH:$PWD` donne ceci: `PATH=/Users/sbrucker/Projects/21sh`

Concernant le code, pense a utiliser les nouvelles fonctions de la libft, `ft_xstrdup()`, `ft_xmalloc()` etc qui permettent d'exit proprement en cas d'erreur de malloc plutot que de renvoyer `NULL`. Vu la structure de ton code par exemple, si un malloc echoue dans `ht_newnode()`, tu vas forcement segfault dans `ht_set()`.

Sinon le comportement est nickel, pas trouve de probleme, tout est bon pour moi concernant le fonctionnement, bien joue ! :D

2018-10-26 15:10 UTC, Gamouche approved these changes

2018-10-27 14:30 UTC, SebastienBruckert approved these changes

2018-10-27 14:30 UTC, merged