Non waiting pipes
jjaniec/21sh pull request #46
Opened 2018-10-28 19:58 UTC by jjaniec

- Remake des pipes
- Changement du moment ou on va chercher les binaires dans la table de hash pour gerer les redirections des erreurs style `command not found`
- Adaptation des handlers des signaux sigint et sigchild pour gerer les pipes
- Quelques fonctions qui pourraient etre utiles pour un eventuel job control

2018-10-30 20:15 UTC, Gamouche requested changes
slt el jijito ! j'ai regardé rapidos, voici quelques soucis à régler :

`$ ls | echo`
valgrind sort beaucoup de leaks
pareil pour 
`$ echo lol | echo`
ou encore
`$ echo lol | ls`


leaks aussi avec
`$ /dev/random | cat`
`$ cat | echo`
`$ echo lol` (oui sans pipe, c'est surement parce que c'est fork (inutilement ?) )
`$ les carottes rapees`
`$ crotte`
`$ ls | tacocrotte` (haaa valgrind il dit que la memoire fuit)
`$ /bin/echo lol | syntax off` 
`$ echo lol | exit`
`$ exit | echo lol`

'fin bref toutes ces leaks doivent etres liees (surement que les forkés ne free pas bien)



`$ mkdir janice ; cd janice ; rmdir ../janice ; pwd ; cd ..`
Ah bah ca ne marche pas  :( meme que ca quitte le shell :o

2018-11-01 14:13 UTC, jjaniec commented
@Gamouche slt mon beau gamouche tres bien vu le truc du cd ! Normalement c'est fix on passait dans un exit(MALLOC_ERROR) dans le builtin :(

Par contre pour les leaks mon valgrind a moi me dis rien pour les commandes que tu m'as donne, meme pour les pipes sans execve style `echo | echo` apres il me semble que tu es sur macos et moi linux donc il fonctionne peut etre pas pareil (avec leak-check=full et trace-children=yes) je sais pas, je pourrais pas regarder ca avant de revenir a l'ecole du coup :(

2018-11-05 16:39 UTC, SebastienBruckert requested changes
Ca fonctionne niquel !
Par contre quand je fais des trucs du style `./42sh | cat -e`, puis un Ctrl C, le process de cat se termine, mais pas 42sh. J'ai deux process de 42sh. Je suis dans le groupe du deuxieme 42sh avec par exemple un `sleep`, mais quand j'exit, je quitte les deux 42sh. Ce n'est pas plus mal, mais c'est assez chelou ^^

Sinon c'est top ! <3

2018-11-06 19:38 UTC, Gamouche commented
Salut,
sur la branche non_waiting_pipes il n'y a plus les leaks dont je t'avais parlé. En revanche tu aurais pu tester ton fix du cd, car ok le shell ne quitte plus mais on est coincé sans aucune possibilité de faire quoi que ce soit ... je pense que cela vient du fait que l'appel à getcwd() au debut de builtin_cd() va foirer.

Finalement en retestant avec valgrind comme ceci :
$ valgrind --leak-check=full --show-reachable=yes  --track-origins=yes  ./42sh   2>/dev/ttys001

Ca trouve encore des leaks un peu partout ...

Je n'ai trouvé aucune difference avec la branche childs_minor_changes.

2018-11-07 11:27 UTC, SebastienBruckert approved these changes

2018-11-07 14:44 UTC, cgaspart reviewed
Normalement ça règle le soucis non >?

2018-11-07 14:44 UTC, cgaspart commented on srcs/builtin/builtin_cd.c
>  	if (!(getcwd(cwd, MAX_ENV_ENTRY_LEN)))
```suggestion
	if (!(getcwd(cwd, MAX_ENV_ENTRY_LEN)) && errno != ENOENT)
	{
		if (errno == EACCES)
```
Pour fixe le bug qu'a trouvé @Gamouche

2018-11-07 16:17 UTC, cgaspart approved these changes
Ok pour moi

2018-11-08 15:29 UTC, Gamouche approved these changes

2018-11-09 14:28 UTC, merged