Final prompt
jjaniec/21sh pull request #47
Opened 2018-11-02 14:28 UTC by cgaspart

- Print path (print '~' for $HOME)
- Print git_branch (ty jjaniec)
- Print ('❯ ') to start user input

2018-11-05 16:10 UTC, SebastienBruckert requested changes
Tout fonctionne niquel, juste deux mini trucs au niveau du code, notamment le fait que tu retourne un truc qui a ete free a un moment donne.
C'est beau, well done ! :D

2018-11-05 16:10 UTC, SebastienBruckert commented on srcs/prompt_details/get_git_info.c
> +	if ((l = ft_strlen(hash)) <= COMMIT_HASH_MAX_LEN)
Sonar cloud a raison !

2018-11-05 16:10 UTC, SebastienBruckert commented on srcs/prompt_details/get_git_info.c
> +	return (branch_str);
D'accord aussi avec Sonar cloud, si on passe dans le premier `if`, tu retourne une string qui a ete free :/

2018-11-05 22:18 UTC, SebastienBruckert approved these changes

2018-11-06 16:56 UTC, Gamouche requested changes
Yo, good job c'est super joli !

Je te note ici un petit soucis qu'il serait préférable de régler :

1) Lancer valgrind
$ valgrind --leak-check=full --show-reachable=no  --track-origins=yes  ./42sh   2>/dev/ttys001

2) Ensuite écrire "cd " puis tab puis selectionner ft_printf. Une fois ft_printf selectionné et donc affiché dans la ligne d'édition, valgrind sort des invalid read & stuff liées à l'autoc.

2018-11-09 14:53 UTC, Gamouche approved these changes

2018-11-09 15:06 UTC, merged