Builtin read
jjaniec/21sh pull request #50
Opened 2018-11-11 15:34 UTC by Gamouche

/*
**	builtin read :
**	Wait for the user's input, then split the input into words using IFS,
**	the words are stored in the shell variables given as arguments.
**	If there is more words than variables to store them, the last variable will
**	have all the remaining words.
**	If there is no variable given as argument, the REPLY variable is used.
**
**	option -d x : change the delimiter ('\n' by default) to x.
**	option -n x : read stops if receiving the delimiter character or if it
**	has read x characters. (not compatible with option -N).
**	option -N x : ignore the delimiter character, read stops if it has read
**	x character or encountering EOF. (not compatible with option -n).
**	option -p : a prompt is displayed before reading.
**	option -s : the input is not displayed.
**	issou
*/

Les options et les variables shell doivent obligatoirement etre separees par `--` :  read -d a -n 5 -- var1 var2

Dites-moi s'il y a des bugs ou si valgrind rale :)
Ne regardez pas le code, c'est le pire de la terre. Disons juste qu'il vous permettra de mieux apprécier ce que je fais d'habitude.

2018-11-11 15:48 UTC, jjaniec commented on srcs/exec/exec_thread.c
> +/*   By: cyfermie <cyfermie@student.42.fr>          +#+  +:+       +#+        */
arrete de faire `git add -A` stp :(

2018-11-11 15:48 UTC, jjaniec commented on srcs/main.c
> +	while (!!~!~!~(intptr_t)("taco""cat" - ((0xB16B00B5 ^ 0xDEADC0DE) * (!42))))
beau code / 20

2018-11-11 15:48 UTC, jjaniec commented on includes/forty_two_sh.h
> +typedef int	t_acocat;
je pense que cette ligne devrais etre enlevée pour des raisons évidentes de performaces

2018-11-11 16:01 UTC, Gamouche commented on includes/forty_two_sh.h
> +typedef int	t_acocat;
issou

2018-11-11 16:28 UTC, SebastienBruckert requested changes
Klean ton kode <3
Tout fonctionne, je n'ai pas trouve de leaks !

2018-11-11 16:28 UTC, SebastienBruckert commented on includes/forty_two_sh.h
> +typedef int	t_acocat;
Ceci est une bottleneck !

2018-11-11 16:28 UTC, SebastienBruckert commented on srcs/builtin/builtin_read.c
> +*/
Clean ton kode <3

2018-11-11 16:28 UTC, SebastienBruckert commented on srcs/builtin/builtin_read.c
> +//kk( & options );
Clean this

2018-11-11 16:28 UTC, SebastienBruckert commented on includes/builtins.h
> +int		issou_norme_mdr(int foo, struct s_bltread *options, char **args, unsigned int *i);
Renomme au moins correctement les fonctions qui ne sont pas static

2018-11-11 16:28 UTC, SebastienBruckert commented on srcs/builtin/builtin_read_store_words.c
> +*/
Clean kode

2018-11-11 16:28 UTC, SebastienBruckert commented on srcs/ft_strsplit_by_str.c
> +//#include "../includes/libft.h"
kode clean

2018-11-11 16:28 UTC, SebastienBruckert commented on srcs/ft_strsplit_by_str.c
> +char    *ft_strchr(const char *, int); // en attendant d'inclure libft.h
What's this ?

2018-11-11 20:39 UTC, jjaniec commented on srcs/line_edition/line_edition.c
> +	while (le->key_no != le->le_state.le_char_delim && "cest ta merge la jjaniec")
![db0975046a0133771d8bcddba7e690a9](https://user-images.githubusercontent.com/16088893/48318005-37780f80-e5fa-11e8-8b10-79350174be43.jpg)

2018-11-12 15:29 UTC, Gamouche commented on srcs/line_edition/line_edition.c
> +	while (le->key_no != le->le_state.le_char_delim && "cest ta merge la jjaniec")
issou

2018-11-12 16:21 UTC, jjaniec approved these changes

2018-11-13 13:40 UTC, cgaspart reviewed
Un petit clean ?

2018-11-13 13:40 UTC, cgaspart commented on srcs/builtin/builtin_read.c
> +*/
Ce fichier n'est pas vraiment utile...

2018-11-14 08:13 UTC, SebastienBruckert approved these changes

2018-11-15 13:54 UTC, cgaspart approved these changes

2018-11-19 21:59 UTC, merged